# action.yml
name: 'GDBK Builder'
description: 'Build gdbk sources'
inputs:
  subdirectory:
    description: 'Path to sources'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subdirectory }}