# action.yml
name: 'GBDK Builder'
description: 'Build gbdbk projects'
inputs:
  subdirectory:
    description: 'Path to sources'
    required: false
    default: '.'
branding:
  icon: play-circle
  color: yellow
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subdirectory }}
