name: Example Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build gbdk project
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Build
      uses: ./ # This is only here because the actions is in this repository
      with:
        subdirectory: ./test-sources
    - name: Print out build folder
      run: ls test-sources