name: Example Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build hello world application
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ./
      with:
        subdirectory: ./test-sources